### ISSUE TITLE
Source code location

### ISSUE THREAD

**Issue by Swoogan** [tr808axm/raftmodding-docs#5]
These files state the following:

> Actually the RMLLauncher and Core are open-sourced, then it's analysed by users of this launcher and modders that have the knowledge to analyse it.
> If no one showed it's a virus, it's mainly because it's not, so don't worry 

Where is the source code located? I have searched and cannot find any source code repositories.

**Comment by tr808axm** [comment]
Hey there! I'm sorry I didn't see this issue for a - let's just say - _very_ long time. The source code of the loader is available at https://gitlab.com/TeKGameR950/HyTeKModLoader. I've added this link to the docs now too. Apologies again for the long time-to-response.

Let me know if you find any other issues.

Cheers, traxam
